#!/bin/bash

CURR_PATH=$(realpath $0)
CURR_DIR=$(dirname "$CURR_PATH")

export LIBGL_ALWAYS_SOFTWARE=1
export LD_LIBRARY_PATH=$CURR_DIR/libs:$LD_LIBRARY_PATH

cd $CURR_DIR

./italo-xadrez-app

cd - &> /dev/null
